export const GET_PROMOTIONS = 'GET_PROMOTIONS';
export const UPDATE_PROMOTION = 'UPDATE_PROMOTION';
export const DELETE_PROMOTION = 'DELETE_PROMOTION';
export const DUPLICATE_PROMOTION = 'DUPLICATE_PROMOTION';
export const PROMOTIONS_LOADING = 'PROMOTIONS_LOADING';